version: "3.9"

services:

  redis:
    image: redis
    container_name: pychrono-redis

    ports:
      - "6379:6379"

  nats:
    image: nats
    container_name: pychrono-nats

    command: "-js"

    ports:
      - "4222:4222"
      - "8222:8222"

  api:
    build: .
    container_name: pychrono-api

    env_file:
      - .env

    ports:
      - "8000:8000"

    environment:
      - REDIS_HOST=redis
      - NATS_URL=nats://nats:4222

    depends_on:
      - redis
      - nats

  scheduler:
    build: .
    container_name: pychrono-scheduler

    env_file:
      - .env

    command: python -m scripts.start_scheduler

    environment:
      - REDIS_HOST=redis
      - NATS_URL=nats://nats:4222

    depends_on:
      - redis
      - nats

  worker:
    build: .
    container_name: pychrono-worker

    env_file:
      - .env

    command: python -m scripts.start_worker

    environment:
      - REDIS_HOST=redis
      - NATS_URL=nats://nats:4222

    depends_on:
      - redis
      - nats